os: linux
arch: arm64
dist: bionic
language: java
branches:
  only:
    - master
    - develop
script:
  - ./mvnw
before_install:
  - mv ./target/generated-docs/main.html ./target/generated-docs/index.html
deploy:
  - provider: releases
    token: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      repo: flohero/linux-cheat-sheet-de
  - provider: pages
    token: $GITHUB_TOKEN
    local_dir: "target/generated-docs/"
    skip_cleanup: true
    on:
      repo: flohero/linux-cheat-sheet-de