os: linux
arch: arm64
dist: bionic
language: java
branches:
  only:
    - master
    - develop
script:
  - ./mvnw
deploy:
  - provider: releases
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      repo: flohero/linux-cheat-sheet-de
  - provider: pages
    github_token: $GITHUB_TOKEN
    local_dir: "target/generated-docs/"
    skip_cleanup: true
    on:
      repo: flohero/linux-cheat-sheet-de