os: linux
arch: arm64
dist: bionic
language: java
branches:
  only:
    - master
    - develop
script:
  - ./mvnw
before_deploy:
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
      mv target/generated-docs/main.html target/generated-docs/index.html
    fi
deploy:
  - provider: releases
    token: $GITHUB_TOKEN
    cleanup: false
    skip_cleanup: true
    file:
      - "target/generated-docs/main.pdf"
      - "target/generated-docs/short.pdf"
    on:
      repo: flohero/linux-cheat-sheet-de
  - provider: pages
    token: $GITHUB_TOKEN
    local_dir: "target/generated-docs/"
    cleanup: false
    skip_cleanup: true
    on:
      repo: flohero/linux-cheat-sheet-de